### ISSUE TITLE
Just suggesting...

### ISSUE THREAD

**Issue by mtrif** [gavinlyonsrepo/NOKIA5110_TEXT#2]
Hi,
Two unrelated things here below.

Firstly, please be informed that I'm successfully using your library with ESP8266.
Just is case, somebody will ask you, my LCD connections are as follows:
`NOKIA5110_TEXT mylcd(D2, D1, D6, D7, D5);`
(ESP8266 pins :  D2=GPIO4  D1=GPIO5  D6=GPIO12  D7=GPIO13  D5=GPIO14)
This is not necessarily the best or the unique setup, it is the one that worked for me and allowed me to progress with my experiments. 

Secondly, I do have a suggestion for the next release: add public access to _sleep member
Something like
`bool NOKIA5110_TEXT::LCDIsSleeping() { return _sleep; }`

Keep on !
M.T.

**Comment by gavinlyonsrepo** [comment]
Thanks for feedback and suggestion, will look into it.

**Comment by gavinlyonsrepo** [comment]
HI 

I have included public access to _sleep member in version  2.1.0 just released.

regards
