### ISSUE TITLE
Rotating the screen

### ISSUE THREAD

**Issue by twistms** [gavinlyonsrepo/NOKIA5110_TEXT#5]
Hi! Nice and light library.
Is it possible to change the screen rotation 180 degrees?

**Comment by gavinlyonsrepo** [comment]
Hi 

The  LCD controller cannot rotate the data so it must be done in software.
The way that the larger graphic libraries do it, is with a screen buffer they write to the buffer pixel by pixel, placing the pixel according to the rotation parameter set. Then display the buffer to the screen. 

This library writes the fonts and patterns byte by byte, in vertical mode with NO screen buffer,
This is to keep it lightweight. Adding a buffer defeats purpose of library.
It could be done theoretical without a buffer but it involves a lot of flipping everything around and writing backwards.
It seems like a lot of work at first glance. 

Next time I do an update(If there is another update) I will have a  look to see how hard it is. 
Most likely, no it will not be done.

Regards

**Comment by twistms** [comment]
I'm understood, thank you!
