### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ellenhp** [gavinlyonsrepo/NOKIA5110_TEXT#7]
Could you add a license file to this project so it's clear whether others are allowed to use it and under what terms? It seems ideal for something I'm doing right now but I want to make sure I'm not stepping on toes.

**Comment by gavinlyonsrepo** [comment]
Hi 

There is a LICENSE.md file in the "extras" folder.

regards

**Comment by ellenhp** [comment]
Perfect, thank you! I'm so used to seeing those in the root of a repo that I didn't think to look there.
